#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-04-23"
name = "remix-hono-app"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB" # i.e.
database_id = "65be2dda-134d-410f-a63b-427892c71ed0" 
database_name = "study-remix-hono-app" 
migrations_dir = "drizzle/migrations"
